trigger:
- master
- feature/*

variables:
  isProduction: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  isTest: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/')]
  branchName: $[variables['Build.SourceBranch']]

pool:
  vmImage: 'windows-latest'

resources: 
  repositories:
  - repository: devops
    endpoint: CodRepo
    type: git
    name: cod/Cod.Infrastructures
    ref: main

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Stage
    steps:
    - task: CopyFiles@2
      displayName: 'Drop Static Website'
      inputs:
        Contents: '$(System.DefaultWorkingDirectory)/src/**'
        TargetFolder: $(Build.ArtifactStagingDirectory)
    - publish: $(Build.ArtifactStagingDirectory)/src
      artifact: drop
    - script: echo $(branchName)
    - script: echo $(isProduction)
    - script: echo $(isTest)

- stage: Test
  condition: and(succeeded(), eq(variables.isTest, true))
  jobs:
  - template: pipelines/jobs/StaticWebsiteDeploy.yml@devops
    parameters:
      buildAgentVmImage: 'windows-latest'
      serviceConnectionId: 'ef0e53dc-dfd5-4d75-844e-35829b44e3bb'
      azureServiceConnection: 'xiexie'
      resourceGroupName: 'xiexietest'
      storageAccountName: 'websitexiexietest'
      checkoutDevopsStep:
       checkout: devops

- stage: Production
  condition: and(succeeded(), eq(variables.isProduction, true))
  jobs:
  - template: pipelines/jobs/StaticWebsiteDeploy.yml@devops
    parameters:
      buildAgentVmImage: 'windows-latest'
      serviceConnectionId: 'ef0e53dc-dfd5-4d75-844e-35829b44e3bb'
      azureServiceConnection: 'xiexie'
      resourceGroupName: 'xiexie'
      storageAccountName: 'websitexiexie'
      cdnCustomDomainName: 'www.xiexie.co.nz'
      enableCdn: true
      checkoutDevopsStep:
       checkout: devops