trigger:
- master
- feature/*

variables:
  isProduction: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  isTest: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/')]

pool:
  vmImage: 'windows-latest'

resources: 
  repositories:
  - repository: devops
    endpoint: CodRepo
    type: git
    name: cod/Cod.Infrastructures
    ref: main

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Stage
    steps:
    - task: CopyFiles@2
      displayName: 'Drop Static Website'
      inputs:
        Contents: '$(System.DefaultWorkingDirectory)/src/**'
        TargetFolder: $(Build.ArtifactStagingDirectory)
    - publish: $(Build.ArtifactStagingDirectory)/src
      artifact: drop

- stage: Test
  condition: and(succeeded('Build'), eq(variables.isTest, true))
  jobs:
  - template: pipelines/jobs/StaticWebsiteDeploy.yml@devops
    parameters:
      buildAgentVmImage: 'windows-latest'
      azureServiceConnection: 'xiexie'
      resourceGroupName: 'xiexietest'
      storageAccountName: 'websitexiexietest'
      allowedOrigins: ['https://websitexiexietest.z8.web.core.windows.net']
      checkoutDevopsStep:
       checkout: devops

- stage: Production
  condition: and(succeeded('Build'), eq(variables.isProduction, true))
  jobs:
  - template: pipelines/jobs/StaticWebsiteDeploy.yml@devops
    parameters:
      buildAgentVmImage: 'windows-latest'
      azureServiceConnection: 'xiexie'
      resourceGroupName: 'xiexie'
      storageAccountName: 'websitexiexie'
      cdnCustomDomainName: 'www.xiexie.co.nz'
      allowedOrigins: ['https://www.xiexie.co.nz', 'https://websitexiexie.z8.web.core.windows.net']
      enableCdn: true
      checkoutDevopsStep:
       checkout: devops