trigger:
- master

variables:
  buildAgentVmImage: 'windows-latest'
  serviceConnection: 'xiexie'
  serviceConnectionId: 'ef0e53dc-dfd5-4d75-844e-35829b44e3bb'
  resourceGroupName: 'xiexie'
  cdnCustomDomainName: 'www.xiexie.co.nz'

pool:
  vmImage: $(buildAgentVmImage)

resources: 
  repositories:
  - repository: devops
    endpoint: CodRepo
    type: git
    name: cod/Cod.Infrastructures
    ref: master

stages:
- stage: Production
  jobs:
  - template: pipelines/jobs/StaticWebsiteDeploy.yml@devops
    parameters:
      buildAgentVmImage: $(buildAgentVmImage)
      serviceConnectionId: $(serviceConnectionId)
      azureServiceConnection: $(serviceConnection)
      resourceGroupName: $(resourceGroupName)
      storageAccountName: 'web$(resourceGroupName)'
      cdnCustomDomainName: $(cdnCustomDomainName)
      enableCdn: true
